        delay_low   = $80
        delay_high  = $81
        accumulator = $82
        x_register  = $83
        y_register  = $84
        mpu_status_register = $85
        stack_pointer = $86
        program_counter_low = $87
        program_counter_high = $88
        in_buffer_counter = $89
        in_buffer_head = $8a
        in_buffer_tail = $8b
        index_high = $8c
        index_low = $8d
        
        stack_page  = $100
