;;;
;;  subroutine: EXPLANATION
;;
;;   Preparation:     x: inparameter
;;                    y: inparameter
;;
;;   Returned Values: a: entry value
;;                    x: entry value
;;                    y: entry value
;;
;;   MPU Flags: NVmxDIZC
;;              ||||||||
;;              ||||||||
;;              ||||||||
;;
;;
;;   Examples: ldx value       ;value
;;             ldy $60         ;value
;;             jsr subroutine  ;call subroutine
;;
;;;
